export interface Taxonomy {
  division: string;
  clase: string;
  orden: string;
  familia: string;
  genero: string;
}

export interface Species {
  id: string;
  scientificName: string;
  authority: string;
  family: string;
  genus: string;
  commonName: string;
  taxonomy: Taxonomy;
  altitude: string;
  distribution: string[];
  morphology: string[];
  phenomenology: string[];
  ecology: string;
  photoLabels: string[];
}

export const SPECIES_LIST: Species[] = [
  {
    id: "arenaria-rivularis",
    scientificName: "Arenaria rivularis",
    authority: "R.A. Philippi",
    family: "Caryophyllaceae",
    genus: "Arenaria",
    commonName: "Flor de atacama",
    taxonomy: {
      division: "Magnoliophyta",
      clase: "Magnoliopsida",
      orden: "Caryophyllales",
      familia: "Caryophyllaceae",
      genero: "Arenaria",
    },
    altitude: "3.200 – 4.700 m s.n.m.",
    distribution: ["AYP", "TAR", "ANT", "ATA", "COQ"],
    morphology: [
      "Planta pequeña, de crecimiento bajo (de 2 a 5 cm), que forma céspedes o cojines en bofedales altoandinos o grietas rocosas que poseen humedad.",
      "Tallos glabros (sin pelos o tricomas), cilíndricos, de no más de 5 cm de altura, que crecen apoyándose sobre otras plantas o el sustrato.",
      "Hojas pequeñas (3 mm aprox.), muy juntas entre sí, imbricadas (dispuestas de manera alternada, como las escamas de un pez) y algo carnosas (suculentas), más largas que anchas, glabras, de color verde claro luminoso.",
      "Flores blancas, solitarias, con 5 pétalos ovados y anchos. La base de la flor o cáliz se forma por sépalos glabros, ovado-triangulares de color verde. Posee alrededor de 10 estambres de color blanco o violáceo. Se distingue de las otras especies de Arenaria porque la parte femenina, en el centro de la flor, tiene 3 estilos.",
      "Semillas de color negro brillante, reniformes (en forma de riñón), diminutas, con un tamaño similar a un grano de arena fina o la punta de una aguja de coser.",
    ],
    phenomenology: [
      "Herbácea, con tallos blandos y tiernos, de color verde. Se caracteriza porque sus hojas, aunque pequeñas, son gruesas y algo suculentas, lo que le permite almacenar agua en sus estructuras. Es de crecimiento rastrero, formando alfombras que permiten disminuir la pérdida de agua por evaporación.",
      "Cuenta con un ciclo de vida perenne, es decir, la planta se mantiene viva durante todo el año.",
      "Florece en forma abundante durante la estación estival (diciembre a febrero), pero si eres buen observador, durante todo el año se puede encontrar alguna flor.",
      "Las semillas son liberadas durante el estío o transición entre verano-otoño. Sus semillas entran en dormancia durante la época más fría para luego germinar y crecer durante el calor del verano.",
      "No tiene un síndrome de dispersión especializado, aunque por su diminuto tamaño puede hacerlo por hidrocoria, barocoria o anemocoria.",
    ],
    ecology:
      "Es una especie altoandina que crece entre los 3.200 y 4.700 m s.n.m., típica de vegas, bofedales y márgenes de cursos de agua.",
    photoLabels: ["Foto principal", "Foto flor", "Foto tallo"],
  },
  {
    id: "azorella-cryptantha",
    scientificName: "Azorella cryptantha",
    authority: "(Clos) Reiche",
    family: "Apiaceae",
    genus: "Azorella",
    commonName: "Llareta",
    taxonomy: {
      division: "Magnoliophyta",
      clase: "Magnoliopsida",
      orden: "Apiales",
      familia: "Apiaceae",
      genero: "Azorella",
    },
    altitude: "2.500 – 4.300 m s.n.m.",
    distribution: ["ATA", "COQ"],
    morphology: [
      "Planta de crecimiento cespitoso (con hábito de césped) que forma cojines compactos y hemisféricos. Debido a que el crecimiento tiende a ser más rápido en la periferia que en el centro, la forma, dureza y extensión de las hojas y ramas pueden variar dentro de un mismo individuo.",
      "Tallos cortos con entrenudos cortos que alcanzan apenas unos cm de alto. Los tallos presentan numerosas hojas sésiles, que no tienen pecíolo y se insertan directamente en el tallo. Cuentan con una base amplexicaule. Tienen márgenes lisos, dentados o lacinados, y presentan cilios o diminutas vellosidades.",
      "Inflorescencia en umbela. Su color es amarillo y tienen 5 pétalos; estaminadas en la periferia y perfectas en el centro (hermafroditas).",
      "Fruto ovoide dorsalmente comprimido, terete y de aspecto glabro. Excepcionalmente puede ser escamoso.",
    ],
    phenomenology: [
      "Herbácea xerofítica. Su forma de crecimiento cespitosa le permite reducir la superficie expuesta a evapotranspiración, optimizando el almacenamiento de agua.",
      "Cuenta con un ciclo de vida perenne, es decir mantiene su color verde durante todo el año. Es resistente al estrés hídrico y puede tolerar temperaturas bajo 0.",
      "Florece en la estación estival, entre diciembre y febrero. Los frutos aparecen a finales de febrero y marzo.",
      "El principal síndrome de dispersión es anemocórico (por viento) y barocorico (por gravedad y arrastre).",
      "Su reproducción puede ser sexuada o asexuada por fragmentación de un individuo que genera nuevos vástagos.",
    ],
    ecology:
      "Es una especie típica de la Cordillera de los Andes entre los 2.500 y 4.300 m s.n.m., típica de vegas, bofedales y márgenes de cursos de agua altoandinos.",
    photoLabels: ["Foto principal", "Foto flor", "Foto hoja"],
  },
  {
    id: "calandrinia-compacta",
    scientificName: "Calandrinia compacta",
    authority: "Barnéoud",
    family: "Montiaceae",
    genus: "Calandrinia",
    commonName: "",
    taxonomy: {
      division: "Magnoliophyta",
      clase: "Magnoliopsida",
      orden: "Caryophyllales",
      familia: "Montiaceae",
      genero: "Calandrinia",
    },
    altitude: "1.900 – 4.600 m s.n.m.",
    distribution: ["AYP", "TAR", "ANT", "ATA", "COQ", "RMS"],
    morphology: [
      "De crecimiento bajo, dos a tres cm de altura, adaptadas al crecimiento en condiciones de alta montaña.",
      "Tallos cortos con hojas dispuestas en rosetas densas, de forma lineal dilatadas en la base y ensiformes. Son de textura carnosas suculentas, glabras, pero a veces presentan pequeñas papilas.",
      "Flores con pedúnculo del mismo largo o menor al de las hojas. Tienen 5 a 6 pétalos de color rosa pálido, cuyo cáliz se caracteriza por sépalos anchamente ovado-agudos, de forma entera y glabros. Entre 9 a 14 estambres por flor.",
      "Semillas con forma orbicular-reniformes, de color negro o castaño oscuro y reticuladas.",
    ],
    phenomenology: [
      "Herbácea, que se caracteriza por tallos blandos y tiernos, de color verde. Tiene hábitos suculentos, que le permiten almacenar agua en sus estructuras. Es de crecimiento rastrero formando alfombras.",
      "Su ciclo de vida es perenne, es decir mantiene el verdor durante todo el año. Si bien su forma es delicada, puede resistir temperaturas bajo 0 y condiciones de congelamiento.",
      "Florece en la estación de primavera-verano, coincidiendo con la época de mayor disponibilidad hídrica por el deshielo (entre noviembre y febrero).",
      "Su síndrome de dispersión se asocia a una interacción mutualista con hormigas (mirmecocoria) y posiblemente también por zoocoria.",
    ],
    ecology:
      "Se distribuye entre los 1.900 y 4.600 m s.n.m., típica de vegas, bofedales y márgenes de cursos de agua altoandinos.",
    photoLabels: ["Foto flor", "Foto tallo"],
  },
  {
    id: "carex-melanocystes",
    scientificName: "Carex conf. melanocystes",
    authority: "E. Desvaux",
    family: "Cyperaceae",
    genus: "Carex",
    commonName: "",
    taxonomy: {
      division: "Magnoliophyta",
      clase: "Liliopsida",
      orden: "Poales",
      familia: "Cyperaceae",
      genero: "Carex",
    },
    altitude: "0 – 3.500 m s.n.m.",
    distribution: ["TAR", "ANT", "ATA", "COQ", "VAL", "RMS", "MAG"],
    morphology: [
      "De crecimiento tipo cespitoso, crece en forma de champa o grupos apretados. Alcanza alturas entre 10 hasta 30 cm, con rizoma rastrero, estolonífero, de color marrón oscuro.",
      "Tallos glabros, erectos o ligeramente curvados. Sus hojas son glabras, estrechas, plegadas hacia la base y planas hacia el ápice. De estructura robusta y rígida por la presencia de cristales de sílice.",
      "Inflorescencias como espiga, glabras, de forma lineal-oblonga a oblongo-ovoide. Con numerosas espiguillas casi siempre unisexuales. Las glumas son ovales, castañas y de margen hialino.",
      "Fruto de tipo aquenio, seco y con una sola semilla de forma lenticular.",
    ],
    phenomenology: [
      "Herbácea, de hábitos acuáticos, pues se la suele encontrar en ambientes saturados en agua o bastante húmedos.",
      "Perenne, es decir mantiene su verdor durante todo el año; sin embargo el período de crecimiento más activo es durante la primavera y también el otoño.",
      "Florece en la estación de primavera y suele alcanzar su madurez total en un período de uno a dos años.",
      "El síndrome de dispersión más propio de esta especie es la anemocoria (por viento) e hidrocoria (por el arrastre en los cursos de agua).",
    ],
    ecology:
      "Con una amplia distribución entre los 0 y 3.500 m s.n.m., típica de vegas, bofedales y márgenes de cursos de agua altoandinos. Su distribución se encuentra casi en todo Chile.",
    photoLabels: ["Foto flor", "Foto hoja"],
  },
  {
    id: "cinnagrostis-velutina",
    scientificName: "Cinnagrostis velutina",
    authority: "(Nees & Meyen) P.M. Peterson, Soreng, Romasch. & Barberá",
    family: "Poaceae",
    genus: "Cinnagrostis",
    commonName: "",
    taxonomy: {
      division: "Magnoliophyta",
      clase: "Liliopsida",
      orden: "Poales",
      familia: "Poaceae",
      genero: "Cinnagrostis",
    },
    altitude: "2.300 – 4.200 m s.n.m.",
    distribution: ["AYP", "TAR", "ANT", "ATA", "COQ", "LBO", "MAU", "NUB", "BIO", "ARA"],
    morphology: [
      "Crecen como champas, formando matas densas y compactas de hasta 45 cm de altura.",
      "Los tallos forman cañas delgadas y filiformes; las cañas floríferas son pubescentes y levemente ensanchadas con márgenes hialinos. Las hojas son rígidas, junciformes y punzantes, con ligula triangular y dorso finamente pubescente.",
      "Las inflorescencias son espiciformes, brillantes con pedícelo escabroso. Las glumas tienen forma lanceolada y finamente escabrosa.",
      "Las semillas son frutos secos que no abren al madurar (cariópside), con forma de huso o fusiformes.",
    ],
    phenomenology: [
      "Es una herbácea, es decir sus tallos son suaves y blandos.",
      "Su ciclo de vida es perenne, por lo que mantiene una condición verde y fotosintéticamente activa durante todo el año.",
      "Florece a finales del verano entrando el otoño (entre febrero y mayo).",
      "El síndrome de dispersión característico de las gramíneas es por anemocoria, facilitado por el viento, dado que sus semillas son pequeñas, ligeras y presentan una pequeña plumilla que promueve su volatilidad.",
    ],
    ecology:
      "Es una especie típica de la Cordillera de los Andes entre los 2.300 y 4.200 m s.n.m.",
    photoLabels: ["Foto flor", "Foto tallo"],
  },
  {
    id: "erythranthe-depressa",
    scientificName: "Erythranthe depressa",
    authority: "(R. Philippi) G.L. Nesom",
    family: "Phrymaceae",
    genus: "Erythranthe",
    commonName: "",
    taxonomy: {
      division: "Magnoliophyta",
      clase: "Magnoliopsida",
      orden: "Lamiales",
      familia: "Phrymaceae",
      genero: "Erythranthe",
    },
    altitude: "0 – 3.700 m s.n.m.",
    distribution: ["ANT", "ATA", "COQ"],
    morphology: [
      "De crecimiento rastrero, en las orillas de cuerpos de agua poco profundos; se la puede encontrar donde brotan las vertientes.",
      "Tallos ascendentes, cortos y redondeados, a veces fistulosos (huecos en su interior).",
      "Hojas sésiles, anchamente ovadas, con margen irregular y groseramente dentado o aserrado, de ápice agudo. Dispuestas en posición opuesta y glabras por ambos lados.",
      "Una flor hermafrodita y solitaria sobre un pedícelo axilar tres veces más largo que el cáliz. Tienen cinco pétalos en una corola tubular de color amarillo, con manchas rojas conspicuas que actúan como guía de néctar.",
      "Semillas cafés oscuras, oblongas, reticuladas y apiculadas.",
    ],
    phenomenology: [
      "Herbácea de tallos suaves y blandos, generalmente sumergidos en agua.",
      "Perenne, es decir mantiene su verdor y actividad fotosintética durante todo el año.",
      "Si bien el máximo de floración ocurre durante la primavera y verano temprano (entre septiembre y enero), dada su asociación estricta a ambientes húmedos, se pueden encontrar flores casi todo el año.",
      "El síndrome de dispersión más conocido para esta especie es la barocoria (dispersión por gravedad) y la hidrocoria (dispersión a lo largo de cursos de agua).",
    ],
    ecology:
      "Es una especie propia de ambientes acuáticos en las ecorregiones mediterránea, altiplano y desierto, desde los 0 a 3.700 m s.n.m.",
    photoLabels: ["Foto flor", "Foto hoja"],
  },
  {
    id: "gamocarpha-compacta",
    scientificName: "Gamocarpha compacta",
    authority: "(R. Philippi) S. Denham & Ponzer",
    family: "Calyceraceae",
    genus: "Gamocarpha",
    commonName: "Chicorea",
    taxonomy: {
      division: "Magnoliophyta",
      clase: "Magnoliopsida",
      orden: "Asterales",
      familia: "Calyceraceae",
      genero: "Gamocarpha",
    },
    altitude: "500 – 4.300 m s.n.m.",
    distribution: ["ANT", "ATA", "COQ", "RMS", "MAU"],
    morphology: [
      "De crecimiento rastrero arrosetado, no supera los 3,5 cm de altura y 10 cm de diámetro aproximadamente.",
      "Los tallos son cortos y estoloníferos, crecen a ras de suelo y de sus nudos pueden enraizar y formar nuevas plantas. Sus ramas laterales son frondosas y decumbentes. Las hojas son gruesas, con base atenuada en el pecíolo, con lóbulos irregulares y lineales.",
      "Las flores están organizadas en grupos (inflorescencia) de 25 a 30 flores por capítulo. Las flores blancas son muy pequeñas (5 mm) y tienen 5 a 6 pétalos que forman una corola infundibuliforme.",
      "Frutos secos de tipo aquenio con una sola semilla pequeña y compacta.",
    ],
    phenomenology: [
      "Es una herbácea con hábitos hemicriptófitos, es decir que sus yemas permanecen a ras de suelo durante la época desfavorable. La parte aérea muere anualmente.",
      "Sigue considerándose una especie perenne, dado que cada individuo mantiene sus brotes latentes y no muere completamente.",
      "Florece durante la primavera tardía-verano (noviembre a enero).",
      "Síndrome de dispersión más probable es la anemocoria (por viento), aunque también muestran regeneración vegetativa por estolones.",
    ],
    ecology:
      "Es una especie típica de la Cordillera de los Andes entre los 500 y 4.300 m s.n.m., se encuentra en los alrededores de vegas y bofedales, donde aún persiste humedad en el suelo.",
    photoLabels: ["Foto flor", "Foto hoja"],
  },
  {
    id: "gayophytum-micranthum",
    scientificName: "Gayophytum micranthum",
    authority: "Hooker y Arnott",
    family: "Onagraceae",
    genus: "Gayophytum",
    commonName: "",
    taxonomy: {
      division: "Magnoliophyta",
      clase: "Magnoliopsida",
      orden: "Myrtales",
      familia: "Onagraceae",
      genero: "Gayophytum",
    },
    altitude: "Hasta 4.200 m s.n.m.",
    distribution: ["ANT", "ATA", "COQ", "VAL", "RMS", "LBO", "MAU"],
    morphology: [
      "De crecimiento erecto, de hasta 40 cm en buenas condiciones, con ramificaciones basales casi tan largas como la del tallo principal.",
      "Los tallos son frecuentemente rojizos, glabros, escasamente pubescentes. Las hojas son glabras, sésiles, de forma lineal (5-30 mm x 1-3 mm).",
      "Las flores son subsésiles. El cáliz es glabro a escasamente pubescente, y la corola está formada por cuatro pétalos blancos de 1-2 mm de largo.",
      "Por flor se forman menos de 10 semillas, posicionadas en forma alternada dentro de un fruto con forma de vaina de hasta 10 mm de largo.",
    ],
    phenomenology: [
      "Herbácea que crece en la transición de sistemas azonales hídricos y zonales secos. Su presencia es indicadora de humedad.",
      "Tiene un hábito terófito (anual), es decir completa todo su desarrollo durante la estación favorable. Por lo mismo es difícil registrar su presencia, dada su aparición intermitente.",
      "Florece en la estación de primavera-verano, aunque es una especie adaptada a climas fríos, tolerando temperaturas de hasta -8ºC y nevazones ocasionales.",
    ],
    ecology:
      "Su presencia está restringida a la Cordillera de los Andes. Se la puede encontrar por sobre la línea de crecimiento leñoso. En la Cuenca de Maricunga se la ha observado hasta los 4.200 m s.n.m.",
    photoLabels: ["Foto flor", "Foto hoja"],
  },
  {
    id: "halerpestres-exilis",
    scientificName: "Halerpestres conf. exilis",
    authority: "",
    family: "Ranunculaceae",
    genus: "Halerpestres",
    commonName: "",
    taxonomy: {
      division: "Magnoliophyta",
      clase: "Magnoliopsida",
      orden: "Ranunculales",
      familia: "Ranunculaceae",
      genero: "Halerpestres",
    },
    altitude: "Zonas SVAHT",
    distribution: ["ARI-PAR", "TAR", "ANT", "ATA", "COQ"],
    morphology: [
      "Según el ambiente puede tener un crecimiento rastrero (en suelos húmedos) o crecimiento erecto cuando se encuentran dentro de un cuerpo de agua.",
      "Los tallos pueden alcanzar hasta 50 cm, con cualidades radicantes en los nudos. Las hojas son largamente pecioladas, de tonalidades rojizas a veces, poco pubescentes, de forma suborbicular o casi redondas, con bordes irregularmente crenulados y tres nervios principales.",
      "Las flores solitarias pueden ser largamente pedunculadas (4-30 cm). Cada flor tiene 5 a 6 pétalos principalmente amarillos (aunque hay ejemplares con flores blancas). El cáliz está formado por seis a cinco sépalos amarillos ovados o suborbiculares.",
      "Producen frutos secos de tipo aquenio con una sola semilla pequeña.",
    ],
    phenomenology: [
      "Herbácea de tallos suaves y delicados, adaptados a condiciones de alta humedad, incluso quedar completamente sumergidos en agua.",
      "Es una especie perenne.",
      "Florece principalmente durante el verano, pero las flores se pueden observar hasta el otoño temprano (marzo-abril).",
      "El principal síndrome de dispersión de esta especie es la zoocoria y probablemente por el consumo de insectos, así como la anemocoria.",
    ],
    ecology:
      "Es una especie que habita en zonas de gran altitud, típica de los sistemas vegetacionales azonales hídricos terrestres (SVAHT). A veces se encuentra dentro de cojines formados por Oxychloe andina o Zameioscirpus atacamensis.",
    photoLabels: ["Foto flor", "Foto hoja"],
  },
  {
    id: "lobelia-spp",
    scientificName: "Lobelia spp.",
    authority: "",
    family: "",
    genus: "Lobelia",
    commonName: "",
    taxonomy: {
      division: "",
      clase: "",
      orden: "",
      familia: "",
      genero: "Lobelia",
    },
    altitude: "",
    distribution: [],
    morphology: [
      "Según el ambiente puede tener un crecimiento rastrero (en suelos húmedos) o crecimiento erecto cuando se encuentran dentro de un cuerpo de agua.",
      "Los tallos pueden alcanzar de hasta 50 cm, con cualidades radicantes en los nudos.",
      "Las hojas son largamente pecioladas, de tonalidades rojizas a veces, poco pubescentes, de forma suborbicular, con bordes irregularmente crenulados.",
      "Las flores solitarias pueden ser largamente pedunculadas (4-30 cm). Cada flor tiene 5 a 6 pétalos principalmente amarillos. Producen frutos secos de tipo aquenio.",
    ],
    phenomenology: [
      "Herbácea de tallos suaves y delicados, adaptados a condiciones de alta humedad.",
      "Es una especie perenne.",
      "Florece principalmente durante el verano, pero las flores se pueden observar hasta el otoño temprano (marzo-abril).",
    ],
    ecology: "Especie de bofedales y ambientes húmedos altoandinos. Información taxonómica en proceso de verificación.",
    photoLabels: ["Foto flor", "Foto hoja"],
  },
  {
    id: "oxychloe-andina",
    scientificName: "Oxychloe andina",
    authority: "R.A. Philippi (1860)",
    family: "Juncaceae",
    genus: "Oxychloe",
    commonName: "Pukko / Pako",
    taxonomy: {
      division: "Magnoliophyta",
      clase: "Liliopsida",
      orden: "Poales",
      familia: "Juncaceae",
      genero: "Oxychloe",
    },
    altitude: "3.000 – 5.000 m s.n.m.",
    distribution: ["ARI-PAR", "TAR", "ANT", "ATA", "COQ", "RMS"],
    morphology: [
      "De crecimiento bajo, forma cojines densos y punzantes de aproximadamente 30 cm de espesor y alcanzando varios metros de diámetro.",
      "Tallos perennes, lisos de crecimiento rastreros, con parte de su estructura sumergida en agua.",
      "Las hojas, rosetadas en la base, forman vainas que terminan en dos aurículas redondeadas, con un ápice puntiagudo y punzante al tacto.",
      "Especie dioica (flores masculinas y femeninas en individuos distintos). Las flores masculinas son largamente pedunculadas y las femeninas sésiles, ambas de colores púrpura a rojizo.",
      "El fruto es de color rojo intenso, purpúreo, seco que se abre en su madurez. Cada cápsula puede contener entre 40 a 70 semillas de forma ovalada, de color amarillo-ocre.",
    ],
    phenomenology: [
      "Herbácea. Perenne, es decir mantiene su verdor durante todo el año.",
      "Florece en la estación estival (verano), en lo que se conoce como invierno altiplánico, entre octubre y marzo, con un pico entre diciembre y enero.",
      "Síndrome de dispersión de tipo barocoria (dispersión por gravedad), anemocoria (dispersión por viento) o por salpicadura.",
    ],
    ecology:
      "Se encuentran en la región altiplánica de los Andes centrales, entre los 15°30' S y los 27°30' S. El rango de altitud se encuentra entre los 3.000 y 5.000 m s.n.m. El pako es una especie constitutiva de los bofedales que cumple un rol clave en la regulación de la disponibilidad hídrica, actuando como esponja que almacena y libera agua.",
    photoLabels: ["Foto flor masculina", "Foto flor femenina", "Foto hojas en rosetas"],
  },
  {
    id: "phylloscirpus-acaulis",
    scientificName: "Phylloscirpus acaulis",
    authority: "(Phil.) Goetgh. & D.A. Simpson",
    family: "Cyperaceae",
    genus: "Phylloscirpus",
    commonName: "",
    taxonomy: {
      division: "Magnoliophyta",
      clase: "Liliopsida",
      orden: "Poales",
      familia: "Cyperaceae",
      genero: "Phylloscirpus",
    },
    altitude: "3.200 – 4.700 m s.n.m.",
    distribution: ["AYP", "TAR", "ANT", "ATA", "COQ"],
    morphology: [
      "De crecimiento cespitoso, forma densas carpetas creando superficies de tipo césped.",
      "Los tallos crecen en forma rastrera, muy cerca del suelo (acaulis = sin tallo evidente). Sus hojas también son cortas lineares, finas y suelen tener una disposición basal como en roseta.",
      "Las flores se agrupan en inflorescencias con forma de pequeñas cabezuelas de 10-15 mm de diámetro, compuestas por tres a seis espiguillas, sobre un pedúnculo que sobresale hasta 5 cm.",
      "Como fruto producen un utrículo triangular de color brillante oscuro, con una longitud aproximada de 2 mm.",
    ],
    phenomenology: [
      "Herbácea, que se encuentra habitualmente en las zonas más secas de un bofedal.",
      "Perenne, es decir mantiene su verdor durante todo el año.",
      "Florece en primavera temprana, apenas ocurren los primeros deshielos, y las flores se pueden mantener hasta finales de febrero-principios de marzo.",
      "Síndrome de dispersión preferencial de esta especie es la anemocoria (dispersión por el viento).",
    ],
    ecology:
      "Es una especie típica de la Cordillera de los Andes entre los 3.200 y 4.700 m s.n.m. Su distribución abarca el noroeste de Argentina, parte de Bolivia y en Chile: Atacama, Antofagasta y Tarapacá.",
    photoLabels: ["Foto flor", "Foto hoja"],
  },
  {
    id: "puccinellia-frigida",
    scientificName: "Puccinellia frigida",
    authority: "",
    family: "Poaceae",
    genus: "Puccinellia",
    commonName: "",
    taxonomy: {
      division: "Magnoliophyta",
      clase: "Liliopsida",
      orden: "Poales",
      familia: "Poaceae",
      genero: "Puccinellia",
    },
    altitude: "2.300 – 4.500 m s.n.m.",
    distribution: ["AYP", "TAR", "ANT", "ATA", "COQ"],
    morphology: [
      "Esta gramínea tiene un crecimiento erguido. Forma céspedes compactos, densos y en forma de almohadillas.",
      "Los tallos pueden alcanzar 35 hasta 50 cm de altura, articulados como cañas con nudos y entrenudos cilíndricos. Las hojas son láminas erectas y angostas; presentan ligulas membranáceas que evitan el ingreso de agua, polvo o patógenos.",
      "Esta especie genera espiguillas verdosas, glabras, con 2-5 flores, que se ordenan en inflorescencias tipo panícula con pedícelos y ramas escabrosos. Las glumas son desiguales: la inferior más corta y la superior anchamente ovada.",
      "Producen un fruto tipo cariópside de color castaño-claro, finamente reticulado.",
    ],
    phenomenology: [
      "Herbácea, que crece en suelos hidromórficos permanentemente saturados en agua. Está adaptada a condiciones extremas de alta montaña, puede llegar a soportar temperaturas de hasta -15ºC o -20ºC.",
      "Habitualmente presenta un hábito perenne, pero ante periodos con mayor estrés ambiental puede tener hábito anual.",
      "El pico de florecimiento ocurre en primavera (septiembre-octubre), pero se pueden encontrar inflorescencias envejecidas durante el verano.",
      "Síndrome de dispersión por anemocoria (viento) principalmente.",
    ],
    ecology:
      "Es una especie típica de la Cordillera de los Andes entre los 2.300 a 4.500 m s.n.m., típica de vegas, bofedales y márgenes de cursos de agua altoandinos.",
    photoLabels: ["Foto flor", "Foto hojas"],
  },
  {
    id: "triglochin-concinna",
    scientificName: "Triglochin concinna",
    authority: "J. Burtt Davy",
    family: "Juncaginaceae",
    genus: "Triglochin",
    commonName: "",
    taxonomy: {
      division: "Magnoliophyta",
      clase: "Liliopsida",
      orden: "Alismatales",
      familia: "Juncaginaceae",
      genero: "Triglochin",
    },
    altitude: "0 – 3.900 m s.n.m.",
    distribution: ["AYP", "TAR", "ANT", "ATA", "COQ", "MAG"],
    morphology: [
      "De crecimiento estolonífero, es decir rebrota de los tallos.",
      "Tallos glabros, de 3 a 50 cm de altura, de color verde. El escapo o tallo floral es terete (cilíndrico) y hueco, de color verdoso oscuro a violáceo y sobresale entre 10 a 90 cm.",
      "Hojas erectas glabras, ovaladas y semicilíndricas con vainas de márgenes hialinos superpuestos y ligulas agudas.",
      "Inflorescencias con forma de racimo; flores dispuestas en verticilios de 3 a 4 de tonalidad violácea. Habitualmente pueden haber hasta 10 flores por escapo.",
      "Semillas de color amarillento a marrón claro, triangular y redondeadas en la sección transversal.",
    ],
    phenomenology: [
      "Herbácea. Perenne, es decir mantiene su tonalidad verde durante todo el año. Se desarrolla lentamente, en particular durante sus primeros tres años.",
      "En el altiplano florece durante el verano (enero a marzo), y a medida que se desplaza hacia el sur, la floración se adelanta a primavera.",
      "Síndrome de dispersión principalmente por bulbos, que crecen durante otoño-invierno para estar maduros en primavera. Rara vez se reproducen sexualmente.",
    ],
    ecology:
      "Es una especie típica de la Cordillera de los Andes entre los 0 hasta los 3.900 m s.n.m., típica de vegas, bofedales y márgenes de cursos de agua altoandinos.",
    photoLabels: ["Foto flor", "Foto hoja"],
  },
  {
    id: "triglochin-palustris",
    scientificName: "Triglochin palustris",
    authority: "",
    family: "Juncaginaceae",
    genus: "Triglochin",
    commonName: "",
    taxonomy: {
      division: "Magnoliophyta",
      clase: "Liliopsida",
      orden: "Alismatales",
      familia: "Juncaginaceae",
      genero: "Triglochin",
    },
    altitude: "0 – 3.900 m s.n.m.",
    distribution: ["AYP", "TAR", "ANT", "ATA", "COQ", "MAG"],
    morphology: [
      "De crecimiento estolonífero, glabra, de 3 a 50 cm de altura.",
      "Hojas erectas, ovaladas y semicilíndricas con vainas de márgenes hialinos superpuestos y ligulas agudas. Con escapo liso de 10 a 90 cm de alto, terete y hueco.",
      "Inflorescencias con forma de racimo, con flores dispuestas en verticilios de 3 a 4 que separan al alargarse el escapo. Tonalidades violáceas, hasta 10 flores por espécimen.",
      "Semillas de color amarillento a marrón claro, triangular y redondeadas en la sección transversal.",
    ],
    phenomenology: [
      "Herbácea de reproducción bulbar (rara vez se reproducen sexualmente).",
      "Perenne.",
      "Síndrome de dispersión por bulbos que crecen durante otoño-invierno para estar maduros en primavera.",
    ],
    ecology:
      "Es una especie típica de la Cordillera de los Andes entre los 0 hasta los 3.900 m s.n.m., típica de vegas, bofedales y márgenes de cursos de agua altoandinos.",
    photoLabels: ["Foto flor", "Foto tallo"],
  },
  {
    id: "zameioscirpus-atacamensis",
    scientificName: "Zameioscirpus atacamensis",
    authority: "(Phil.) S. Dhooge & P. Goetghebeuer",
    family: "Cyperaceae",
    genus: "Zameioscirpus",
    commonName: "",
    taxonomy: {
      division: "Magnoliophyta",
      clase: "Liliopsida",
      orden: "Poales",
      familia: "Cyperaceae",
      genero: "Zameioscirpus",
    },
    altitude: "3.200 – 4.700 m s.n.m.",
    distribution: ["TAR", "ANT", "ATA"],
    morphology: [
      "De crecimiento cespitoso, forma cojines densos como carpetas de césped de 1,5 a 11 cm de espesor y puede alcanzar varios metros de diámetro.",
      "Los tallos (culmos) son teretes, no ramificados, con su parte inferior a veces inflada. Presentan un crecimiento rastreros, con parte de su estructura sumergida en agua.",
      "Las hojas son basales, en forma rosetadas, con una ligula y un ápice espatulado suave al tacto. Sus vainas foliares son de apariencia pardo-marrón, persistentes en la base.",
      "Cuenta con una inflorescencia de una sola espiguilla terminal con 3 a 18 glumas, lo que les da una apariencia 'chascona'. Todas las glumas son fértiles y las inflorescencias son hermafroditas.",
      "El fruto es obovado y finamente reticulado.",
    ],
    phenomenology: [
      "Herbácea. Perenne, es decir mantiene su verdor durante todo el año.",
      "Florece en la estación estival (verano), en lo que se conoce como invierno altiplánico, entre octubre y marzo, con un pico entre diciembre y enero.",
      "Síndrome de dispersión de tipo barocoria (dispersión por gravedad), anemocoria (dispersión por viento) o por salpicadura.",
    ],
    ecology:
      "Es una especie típica de la Cordillera de los Andes entre los 3.200 y 4.700 m s.n.m. Su distribución abarca el noroeste de Argentina, parte de Bolivia y en Chile: Atacama, Antofagasta y Tarapacá. Género recientemente descrito (2003).",
    photoLabels: ["Foto flor", "Foto hoja"],
  },
];
